### ISSUE TITLE
Does this work with the new embeddings that openAI has released

### ISSUE THREAD

**Issue by gbertb** [maxkrieger/spaceshifter#1]
Just curious if this would work on the new embeddings? Will give it a shot if it does

**Comment by maxkrieger** [comment]
Hey! It does not yet, which is a good reminder that I should clean up this section of the code https://github.com/maxkrieger/spaceshifter/blob/main/src/lib/EmbeddingCache.ts#L52C25-L64C11

I'll get back to you if I merge a fix soon.

**Comment by maxkrieger** [comment]
There's now a dropdown to select the embedding model @gbertb! Thanks for waiting, been busy.
